# Generated by Django 5.2.3 on 2025-06-24 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('field', models.CharField(choices=[('العلوم التجريبية', 'العلوم التجريبية'), ('الرياضيات', 'الرياضيات'), ('التقني الرياضي', 'التقني الرياضي'), ('التسيير والاقتصاد', 'التسيير والاقتصاد'), ('الآداب والفلسفة', 'الآداب والفلسفة'), ('اللغات الأجنبية', 'اللغات الأجنبية')], max_length=30)),
                ('coefficient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('العلوم التجريبية', 'العلوم التجريبية'), ('الرياضيات', 'الرياضيات'), ('التقني الرياضي', 'التقني الرياضي'), ('التسيير والاقتصاد', 'التسيير والاقتصاد'), ('الآداب والفلسفة', 'الآداب والفلسفة'), ('اللغات الأجنبية', 'اللغات الأجنبية')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('school_name', models.CharField(blank=True, max_length=30, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('reports', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('reports', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reply')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='main.question')),
            ],
            options={
                'verbose_name_plural': 'Replies',
            },
        ),
        migrations.CreateModel(
            name='ImageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reply')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('TEXT_BOOKS', 'TEXT_BOOKS'), ('NOTES', 'NOTES'), ('VIDEO', 'VIDEO'), ('SUMMARY', 'SUMMARY'), ('EXAM', 'EXAM')], max_length=20)),
                ('labels', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('additional_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reports', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main.subject')),
            ],
        ),
    ]
