# Generated by Django 5.2.3 on 2025-06-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(choices=[('علوم تجريبية', 'علوم تجريبية'), ('رياضيات', 'رياضيات'), ('تقني رياضي', 'تقني رياضي'), ('تسيير و اقتصاد', 'تسيير و اقتصاد'), ('آداب و فلسفة', 'آداب و فلسفة'), ('لغات أجنبية', 'لغات أجنبية')], max_length=21),
        ),
        migrations.AlterField(
            model_name='subject',
            name='field',
            field=models.CharField(choices=[('علوم تجريبية', 'علوم تجريبية'), ('رياضيات', 'رياضيات'), ('تقني رياضي', 'تقني رياضي'), ('تسيير و اقتصاد', 'تسيير و اقتصاد'), ('آداب و فلسفة', 'آداب و فلسفة'), ('لغات أجنبية', 'لغات أجنبية')], max_length=30),
        ),
    ]
