# Generated by Django 5.2.3 on 2025-07-29 11:22

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('علوم تجريبية', 'علوم تجريبية'), ('رياضيات', 'رياضيات'), ('تقني رياضي', 'تقني رياضي'), ('تسيير و اقتصاد', 'تسيير و اقتصاد'), ('آداب و فلسفة', 'آداب و فلسفة'), ('لغات أجنبية', 'لغات أجنبية')], max_length=30),
        ),
    ]
