# Generated by Django 5.2.3 on 2025-07-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subject_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.question'),
        ),
        migrations.AlterField(
            model_name='imagereply',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.reply'),
        ),
    ]
